from django.conf.urls.defaults import patterns, url
from django.views.generic.simple import redirect_to
from django.conf import settings

from . import views

products = r'/products/(?P<product>\w+)'
versions = r'/versions/(?P<versions>[;\w\.()]+)'
days = r'/days/(?P<days>\d+)'
crash_type = r'/crash_type/(?P<crash_type>\w+)'
os_name = r'/os_name/(?P<os_name>[\w\s]+)'

urlpatterns = patterns('',
    url('^home' + products + '/$',
        views.products,
        name='crashstats.home'),
    url('^home' + products + '$',
        views.products,
        name='crashstats.home'),
    url('^home' + products + versions + '$',
        views.products,
        name='crashstats.home'),
    url('^home' + products + versions + days + '$',
        views.products,
        name='crashstats.home'),
    url('^topcrasher' + products + '$',
        views.topcrasher,
        name='crashstats.topcrasher'),
    url('^topcrasher' + products + versions + '$',
        views.topcrasher,
        name='crashstats.topcrasher'),
    url('^topcrasher' + products + versions + days + '$',
        views.topcrasher,
        name='crashstats.topcrasher'),
    url('^topcrasher' + products + versions + days + crash_type + '$',
        views.topcrasher,
        name='crashstats.topcrasher'),
    url('^topcrasher' + products + versions + days + crash_type + os_name + '$',
        views.topcrasher,
        name='crashstats.topcrasher'),
    url('^daily' + products + '$',
        views.daily,
        name='crashstats.daily'),
    url('^daily' + products + versions + '$',
        views.daily,
        name='crashstats.daily'),
    url('^builds' + products + '$',
        views.builds,
        name='crashstats.builds'),
    # note the deliberate omission of the ';' despite calling the regex variable 'versionS'
    url('^builds' + products + '/versions/(?P<versions>[\w\.()]+)' + '$',
        views.builds,
        name='crashstats.builds'),
    url('^builds' + products + '/rss$',
        views.BuildsRss(),
        name='crashstats.buildsrss'),
    url('^builds' + products + versions + '/rss$',
        views.BuildsRss(),
        name='crashstats.buildsrss'),
    url('^hangreport' + products + '$',
        views.hangreport,
        name='crashstats.hangreport'),
    url('^hangreport' + products + versions + '$',
        views.hangreport,
        name='crashstats.hangreport'),
    url('^hangreport' + products + versions + days + '$',
        views.hangreport,
        name='crashstats.hangreport'),
    url('^topchangers' + products + '$',
        views.topchangers,
        name='crashstats.topchangers'),
    url('^topchangers' + products + versions + '$',
        views.topchangers,
        name='crashstats.topchangers'),
    url('^topchangers' + products + versions + days + '$',
        views.topchangers,
        name='crashstats.topchangers'),
    url(r'^report/list$',
        views.report_list,
        name='crashstats.report_list'),
    url(r'^report/index/(?P<crash_id>.*)$',
        views.report_index,
        name='crashstats.report_index'),
    url(r'^query/$',
        views.query,
        name='crashstats.query'),
    url(r'^query/query$',
        redirect_to, {'url': '/query/?',
                      'permanent': False,
                      'query_string': True}),
    url(r'^buginfo/bug', views.buginfo,
        name='crashstats.buginfo'),
    url(r'^topcrasher/plot_signature/(?P<product>\w+)/(?P<versions>[;\w\.()]+)/(?P<start_date>[0-9]{4}-[0-9]{2}-[0-9]{2})/(?P<end_date>[0-9]{4}-[0-9]{2}-[0-9]{2})/(?P<signature>.*)',
        views.plot_signature,
        name='crashstats.plot_signature'),
    url(r'^signature_summary/json_data$',
        views.signature_summary,
        name='crashstats.signature_summary'),
    # if we do a permanent redirect, the browser will "cache" the redirect and
    # it will make it very hard to ever change the DEFAULT_PRODUCT
    url(r'^$', redirect_to, {'url': '/home/products/%s' % settings.DEFAULT_PRODUCT,
                             'permanent': False}),
)
